from .Doma import DomProdazaAdmin
from .MaloEtaznoeStroitelstvo import MaloEtaznoeStroitelstvoProdazaAdmin
from .KvartiraVtorichka import KvartiraVtorichkaProdazaAdmin
from .KvartiraPervichka import KvartiraPervichkaProdazaAdmin
from .Uchastki import UchactkiProdazaAdmin
from .Komerchiskie import KomerchiskieProdazaAdmin
from .Nezilie import NezelieProdazaAdmin