# Generated by Django 3.0.13 on 2021-05-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('modalnoe_okno_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalnoeOknoPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='modalnoe_okno_plugin_modalnoeoknopluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('yakor', models.CharField(blank=True, help_text='у кнопки не забыть data-toggle="modal" data-target="#example"', max_length=255, null=True, verbose_name='Якорь')),
                ('zagolovok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Модальное окно',
                'verbose_name_plural': 'Модальное окно',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='zakazaniezvonki',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='FormaObratnoiSviaziSetting',
        ),
        migrations.DeleteModel(
            name='ZakazanieZvonki',
        ),
    ]
