# Generated by Django 3.0.13 on 2021-04-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtziviLvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='otzivi_plugin_otzivilvpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в структуре-дереве')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Классы')),
                ('css_style', models.TextField(blank=True, null=True, verbose_name='Стили')),
            ],
            options={
                'verbose_name': 'Отзывы слайдер',
                'verbose_name_plural': 'Отзывы слайдеры',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OtzivDliaPlugina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=255, verbose_name='Автор')),
                ('opisanie', models.TextField(verbose_name='Отзыв')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата и время')),
                ('ssilla', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('ozenka', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Оценка')),
                ('otziv_slaider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otzivi_set', to='otzivi_plugin.OtziviLvPluginSetting', verbose_name='Отзыв слайдер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
            },
        ),
    ]
