# Generated by Django 3.0.13 on 2021-05-29 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedvizkaFiltriPoiskaPluginPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_plugins_nedvizkafiltripoiskapluginpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('tip_nedvizki', models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('dom_arenda', 'Дом-аренда')], max_length=255, verbose_name='Тип недвижки')),
            ],
            options={
                'verbose_name': 'Недвижка. Фильтры/поиск',
                'verbose_name_plural': 'Недвижка. Фильтры/поиск',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NedvizkaIzbranoePluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_plugins_nedvizkaizbranoepluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
            ],
            options={
                'verbose_name': 'Недвижка. Избранное',
                'verbose_name_plural': 'Недвижка. Избранное',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NedvizkaPanelUpravleniaPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_plugins_nedvizkapanelupravleniapluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('pokazat_kartu', models.BooleanField(default=True, verbose_name='Показывать карту')),
                ('pokazat_sortirovku', models.BooleanField(default=True, verbose_name='Показывать сортировку')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
            ],
            options={
                'verbose_name': 'Недвижка. Избранное',
                'verbose_name_plural': 'Недвижка. Избранное',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NedvizkaSpisokObiectovPluginPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_plugins_nedvizkaspisokobiectovpluginpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('tip_nedvizki', models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('dom_arenda', 'Дом-аренда')], max_length=255, verbose_name='Тип недвижки')),
                ('obiectov_na_stranize', models.IntegerField(default=10, verbose_name='Выводить по ')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
            ],
            options={
                'verbose_name': 'Недвижка. Список объектов',
                'verbose_name_plural': 'Недвижка. Список объектов',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
