# Generated by Django 3.0.13 on 2021-06-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nedvizka_plugins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nedvizkapanelupravleniapluginsetting',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='NedvizkaIzbranoePluginSetting',
        ),
        migrations.DeleteModel(
            name='NedvizkaPanelUpravleniaPluginSetting',
        ),
    ]
