# Generated by Django 3.0.13 on 2021-06-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka_plugins', '0002_auto_20210601_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvizkafiltripoiskapluginpluginsetting',
            name='tip_nedvizki',
            field=models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('dom_arenda', 'Дом-аренда'), ('kvartira_prodaza', 'Квартира-продажа'), ('kvartira_arenda', 'Квартира-аренда')], max_length=255, verbose_name='Тип недвижки'),
        ),
        migrations.AlterField(
            model_name='nedvizkaspisokobiectovpluginpluginsetting',
            name='tip_nedvizki',
            field=models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('dom_arenda', 'Дом-аренда'), ('kvartira_prodaza', 'Квартира-продажа'), ('kvartira_arenda', 'Квартира-аренда')], max_length=255, verbose_name='Тип недвижки'),
        ),
    ]
