# Generated by Django 3.0.13 on 2021-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka_plugins', '0004_auto_20210602_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nedvizkafiltripoiskapluginpluginsetting',
            name='tip_nedvizki',
            field=models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('kvartira_pervicka_prodaza', 'Квартира первичка - продажа'), ('kvartira_vtoricka_prodaza', 'Квартира вторичка - продажа'), ('kvartira_vtoricka_prodaza', 'Квартира вторичка - продажа'), ('uchactki_prodaza', 'Участки - продажа'), ('nezilie_prodaza', 'Нежилые - продажа'), ('komerchiskie_prodaza', 'Комерчиские - продажа'), ('maloetaznoe_stroitelstvo', 'Малоэтажное строительство')], max_length=255, verbose_name='Тип недвижки'),
        ),
        migrations.AlterField(
            model_name='nedvizkaspisokobiectovpluginpluginsetting',
            name='tip_nedvizki',
            field=models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('kvartira_pervicka_prodaza', 'Квартира первичка - продажа'), ('kvartira_vtoricka_prodaza', 'Квартира вторичка - продажа'), ('kvartira_vtoricka_prodaza', 'Квартира вторичка - продажа'), ('uchactki_prodaza', 'Участки - продажа'), ('nezilie_prodaza', 'Нежилые - продажа'), ('komerchiskie_prodaza', 'Комерчиские - продажа'), ('maloetaznoe_stroitelstvo', 'Малоэтажное строительство')], max_length=255, verbose_name='Тип недвижки'),
        ),
    ]
