# Generated by Django 3.0.10 on 2020-11-08 11:46

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaObratnoiSviaziSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formi_obratnoi_sviazi_formaobratnoisviazisetting', serialize=False, to='cms.CMSPlugin')),
                ('zagolovok', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('podpis', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Подпись')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
