# Generated by Django 3.0.10 on 2020-11-08 12:20

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('formi_obratnoi_sviazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formaobratnoisviazisetting',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
