# Generated by Django 3.0.10 on 2020-11-08 12:21

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formi_obratnoi_sviazi', '0002_formaobratnoisviazisetting_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaobratnoisviazisetting',
            name='zagolovok',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
