# Generated by Django 3.0.10 on 2020-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formi_obratnoi_sviazi', '0003_auto_20201108_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaobratnoisviazisetting',
            name='zagolovok',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
