# Generated by Django 3.0.13 on 2021-04-12 02:11

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsilkaNavbarePluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ssilka_navbar_plugin_ssilkanavbarepluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('external_link', models.CharField(blank=True, max_length=2040, verbose_name='Внешняя ссылка')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
                ('file_link', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='Ссылка на файл')),
                ('internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Внутренняя ссылка')),
            ],
            options={
                'verbose_name': 'Навбарная ссылка',
                'verbose_name_plural': 'Навбарная ссылка',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
