# Generated by Django 3.0.10 on 2020-10-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PochemuMiDvVideoPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pochemu_mi_pochemumidvvideopluginsetting', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Слайд видео',
                'verbose_name_plural': 'Слайд видео',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PochemuMiLvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='pochemu_mi_pochemumilvpluginsetting', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Полноэкранный слайдер',
                'verbose_name_plural': 'Полноэкранный слайдер',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
