# Generated by Django 3.0.10 on 2020-11-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochemu_mi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pochemumidvvideopluginsetting',
            options={'verbose_name': 'Почему мы - ячейка', 'verbose_name_plural': 'Почему мы - ячейка'},
        ),
        migrations.AlterModelOptions(
            name='pochemumilvpluginsetting',
            options={'verbose_name': 'Почему мы - список', 'verbose_name_plural': 'Почему мы - список'},
        ),
        migrations.AddField(
            model_name='pochemumidvvideopluginsetting',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='pochemumidvvideopluginsetting',
            name='zagolovok',
            field=models.CharField(default='Заголовок', max_length=255, verbose_name='Заголовок'),
        ),
    ]
