# Generated by Django 3.0.10 on 2020-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pochemu_mi', '0002_auto_20201103_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pochemumidvvideopluginsetting',
            name='zagolovok',
            field=models.TextField(default='Заголовок', max_length=255, verbose_name='Заголовок'),
        ),
    ]
