# Generated by Django 3.0.10 on 2020-11-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalereiaLvNaGlavnoiPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='galereia_galereialvnaglavnoipluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея на главной',
                'verbose_name_plural': 'Галерея на главной',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
