# Generated by Django 3.0.13 on 2021-04-14 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaiderSNavigazieiIzobrazeniyamiPluginLvSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='slaider_s_navigaziei_izobrazeniyami_plugin_slaidersnavigazieiizobrazeniyamipluginlvsetting', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок в структурном дереве')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
            ],
            options={
                'verbose_name': 'Слайдер с навигацией изображениями',
                'verbose_name_plural': 'Слайдер с навигацией изображениями',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
