# Generated by Django 3.0.13 on 2021-04-15 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaidersnavigazieiizobrazeniyamipluginlvsetting',
            name='height',
            field=models.IntegerField(default=900, verbose_name='Высота при обрезке'),
        ),
        migrations.AddField(
            model_name='slaidersnavigazieiizobrazeniyamipluginlvsetting',
            name='width',
            field=models.IntegerField(default=1600, verbose_name='Ширина при обрезке'),
        ),
        migrations.CreateModel(
            name='SlaiderSNavigazieiIzobrazeniyamiPluginDvSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('opisanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('index_sortirovki', models.IntegerField(default=0, help_text='Чем больше, тем раньше отобразиться изображение', verbose_name='Индекс сортировки')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('slaider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slaidi_set', to='slaider_s_navigaziei_izobrazeniyami_plugin.SlaiderSNavigazieiIzobrazeniyamiPluginLvSetting')),
            ],
            options={
                'verbose_name': 'Слайд из слайдер с навигацией изображениями',
                'verbose_name_plural': 'Слайд из слайдер с навигацией изображениями',
                'ordering': ['-index_sortirovki'],
            },
        ),
    ]
