# Generated by Django 3.0.13 on 2021-04-15 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0002_auto_20210415_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlaiderSNavigazieiIzobrazeniyamiPluginDvSetting',
            new_name='SlaiderSNavigazieiIzobrazeniyami',
        ),
    ]
