# Generated by Django 3.0.13 on 2021-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0003_auto_20210415_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaidersnavigazieiizobrazeniyami',
            name='zatmenie_color',
            field=models.CharField(blank=True, default='0, 0, 0, 0.1', max_length=255, null=True, verbose_name='Затеменение изображения(r,g,b,a)'),
        ),
    ]
