# Generated by Django 3.0.13 on 2021-04-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0004_slaidersnavigazieiizobrazeniyami_zatmenie_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaidersnavigazieiizobrazeniyami',
            name='opisanie',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
