# Generated by Django 3.0.13 on 2021-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0005_auto_20210415_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaidersnavigazieiizobrazeniyamipluginlvsetting',
            name='speed',
            field=models.IntegerField(default=1500, verbose_name='Скорость смены слайдов(мс)'),
        ),
    ]
