# Generated by Django 3.0.13 on 2021-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaider_s_navigaziei_izobrazeniyami_plugin', '0007_slaidersnavigazieiizobrazeniyamipluginlvsetting_smena_cherez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaidersnavigazieiizobrazeniyamipluginlvsetting',
            name='smena_cherez',
            field=models.IntegerField(default=3000, verbose_name='Смена слайда через (мс)'),
        ),
    ]
