# Generated by Django 3.0.13 on 2021-03-15 09:18

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreneraDvSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='trenera_treneradvsetting', serialize=False, to='cms.CMSPlugin')),
                ('fio', models.CharField(default='-', max_length=255, verbose_name='ФИО')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('ssilka', models.CharField(default='#', max_length=1000, verbose_name='Ссылка')),
                ('opisanie', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тренера - ячейка',
                'verbose_name_plural': 'Тренера - ячейка',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TreneraLvSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='trenera_treneralvsetting', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Тренера - список',
                'verbose_name_plural': 'Тренера - список',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
