# Generated by Django 3.0.13 on 2021-04-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvoiStilIScriptPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='svoi_stili_i_scripti_plugin_svoistiliscriptpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в структуре-дереве')),
                ('type', models.CharField(choices=[('Стиль', 'style'), ('Скрипт', 'script')], default='div', max_length=30, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Мой стиль',
                'verbose_name_plural': 'Мой стиль',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
