# Generated by Django 3.0.13 on 2021-04-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='StilizovaniZagolovokPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stilizovani_zagolovok_plugin_stilizovanizagolovokpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('tag', models.CharField(default='span', max_length=30, verbose_name='Тег')),
                ('text', models.TextField(verbose_name='Текст')),
                ('css_class', models.CharField(default='span', max_length=255, verbose_name='Прочие классы')),
                ('all_style', models.TextField(blank=True, null=True, verbose_name='col стили')),
                ('sm_style', models.TextField(blank=True, null=True, verbose_name='sm стили')),
                ('md_style', models.TextField(blank=True, null=True, verbose_name='md стили')),
                ('lg_style', models.TextField(blank=True, null=True, verbose_name='lg стили')),
                ('xl_style', models.TextField(blank=True, null=True, verbose_name='xl стили')),
            ],
            options={
                'verbose_name': 'Стилизованный заголовок',
                'verbose_name_plural': 'Стилизованный заголовок',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
