# Generated by Django 3.0.13 on 2021-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stilizovani_zagolovok_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stilizovanizagolovokpluginsetting',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочие классы'),
        ),
    ]
