# Generated by Django 3.0.13 on 2021-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoiStilPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='moi_stil_moistilpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('css_classs', models.TextField(blank=True, null=True, verbose_name='Классы')),
                ('css_style', models.TextField(blank=True, null=True, verbose_name='Стили')),
                ('tag_type', models.CharField(default='div', max_length=255, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Мой стиль',
                'verbose_name_plural': 'Мой стиль',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
