# Generated by Django 3.0.13 on 2021-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moi_stil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moistilpluginsetting',
            name='css_classs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Классы'),
        ),
    ]
