# Generated by Django 3.0.13 on 2021-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moi_stil', '0002_auto_20210324_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='moistilpluginsetting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название в структуре-дереве'),
        ),
    ]
