# Generated by Django 3.0.10 on 2020-11-09 15:21

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListDvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='price_list_pricelistdvpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('zagolovok', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('opisanie', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Прайс - слайд',
                'verbose_name_plural': 'Прайс - слайд',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PriceListLvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='price_list_pricelistlvpluginsetting', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Прайс слайдер',
                'verbose_name_plural': 'Прайс слайдер',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
