# Generated by Django 3.0.13 on 2021-03-22 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonovoeIzobrazeniePluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fonovoe_izobrazenie_fonovoeizobrazeniepluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновое изображение',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
