# Generated by Django 3.0.13 on 2021-04-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('fonovoe_izobrazenie_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='crop',
            field=models.BooleanField(default=False, verbose_name='Обрезать'),
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс'),
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='css_style',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS класс'),
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fonovoe_izobrazenie_plugin_fonovoeizobrazeniepluginsetting', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
