# Generated by Django 3.0.13 on 2021-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonovoe_izobrazenie_plugin', '0003_auto_20210410_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='fix_razmer',
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='fix_razmer_height',
            field=models.BooleanField(default=True, verbose_name='Фиксированный размер высоты?'),
        ),
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='fix_razmer_width',
            field=models.BooleanField(default=True, verbose_name='Фиксированный размер ширины?'),
        ),
    ]
