# Generated by Django 3.0.13 on 2021-04-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonovoe_izobrazenie_plugin', '0004_auto_20210410_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='zatmenie_color',
            field=models.CharField(blank=True, default='0, 0, 0, 1', max_length=255, null=True, verbose_name='Затеменение изображения(r,g,b,a)'),
        ),
    ]
