# Generated by Django 3.0.13 on 2021-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonovoe_izobrazenie_plugin', '0005_fonovoeizobrazeniepluginsetting_zatmenie_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='css_style',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль'),
        ),
    ]
