# Generated by Django 3.0.13 on 2021-04-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonovoe_izobrazenie_plugin', '0007_auto_20210415_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonovoeizobrazeniepluginsetting',
            name='css_class_contenta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс контента'),
        ),
    ]
