# Generated by Django 3.0.13 on 2021-05-10 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakazanieZvonki',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formi_obratnoi_sviazi_plugin_zakazaniezvonki', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('perezvonili', models.BooleanField(default=False, verbose_name='Перезвонили?')),
            ],
            options={
                'verbose_name': 'Заказаные обратные звонки',
                'verbose_name_plural': 'Заказаные обратные звонки',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FormaObratnoiSviaziSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='formi_obratnoi_sviazi_plugin_formaobratnoisviazisetting', serialize=False, to='cms.CMSPlugin')),
                ('zagolovok', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('podpis', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Подпись')),
                ('img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
