# Generated by Django 3.0.13 on 2021-04-18 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать на сайте'), (False, 'Не показывать на сайте')], default=True, verbose_name='Показывать')),
                ('tip_operazii', models.IntegerField(choices=[(1, 'Продажа'), (2, 'Аренда')], verbose_name='Тип операции')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('nomer', models.CharField(max_length=50, verbose_name='Номер(id объекта)')),
                ('price_rub', models.FloatField(blank=True, help_text='Оставьте пустым, и сайт предложит пользователю запросить цену', null=True, verbose_name='Цена руб')),
                ('price_dollor', models.FloatField(blank=True, help_text='Оставьте пустым, и сайт предложит пользователю запросить цену', null=True, verbose_name='Цена $')),
                ('obshaia_ploshad', models.FloatField(blank=True, null=True, verbose_name='Общая площадь (кв. м)')),
                ('raspolozenie_gorod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('kordinati_na_karte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кардинаты на карте')),
                ('ploshad_uchastka', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь участка (соток)')),
                ('ploshad_osnovnogo_doma', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь основного дома(кв.м)')),
                ('etaznost', models.IntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('kolvo_komnat', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('kolvo_spalen', models.IntegerField(blank=True, null=True, verbose_name='Количество спален')),
                ('kolvo_sanuzlov', models.IntegerField(blank=True, null=True, verbose_name='Количество санузлов')),
                ('otdelka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отделка')),
                ('mebel', models.BooleanField(blank=True, choices=[(True, 'Есть'), (False, 'Нет')], default=False, max_length=255, null=True, verbose_name='Мебель')),
                ('bassein', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бассейн')),
                ('zona_barbeku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Зона барбекю')),
                ('rastoianie_do_moria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расстояние до моря')),
                ('rastoianie_do_goroda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расстояние до города')),
                ('opisaanaie_kratkoe', models.TextField(blank=True, null=True, verbose_name='Краткое описание для страницы поиска')),
                ('tip_oformlenia_stranizi_obiekta', models.CharField(blank=True, choices=[('sablon', 'Шаблонный(стандартный)'), ('proizvolni', 'Произвольный(можно самому настроить оформление)')], default='sablon', max_length=50, null=True, verbose_name='Тип оформления страницы объекта')),
                ('opisaanaie', models.TextField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание для страницы детальной информации')),
                ('iframe_panorami', models.TextField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание для страницы детальной информации')),
                ('video', models.TextField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Ссылка на видео youtube')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Недвижка',
                'verbose_name_plural': 'Недвижка',
            },
        ),
        migrations.CreateModel(
            name='FotoDomov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nedvizka.Dom', verbose_name='Дом')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото домов',
                'verbose_name_plural': 'Фото домов',
            },
        ),
    ]
