# Generated by Django 3.0.13 on 2021-05-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomArenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать на сайте'), (False, 'Не показывать на сайте')], default=True, verbose_name='Показывать')),
                ('eto_luchoe_prodlozenie', models.IntegerField(choices=[(1, 'Нет'), (2, 'Да. Выводить только на странице лучших предложений'), (3, 'Да. Выводить на странице лучших предложений и главной')], default=1, verbose_name='Лучшее предложение?')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('nomer', models.CharField(max_length=50, verbose_name='Номер(id объекта)')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('price_bazovaia', models.FloatField(blank=True, null=True, verbose_name='Базовая цена руб.')),
                ('prrice_akzionnaia', models.FloatField(blank=True, null=True, verbose_name='Акционная цена руб')),
                ('obshaia_ploshad', models.FloatField(blank=True, null=True, verbose_name='Общая площадь (кв. м)')),
                ('naselenii_punkt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
                ('kordinati_na_karte', models.CharField(blank=True, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте')),
                ('ploshad_uchastka', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь участка (соток)')),
                ('ploshad_osnovnogo_doma', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь основного дома(кв.м)')),
                ('nalichie_gaza', models.BinaryField(default=False, verbose_name='Наличие газа в доме')),
                ('blizost_so_shkoloi', models.BinaryField(default=False, verbose_name='Близость со школой')),
                ('blizost_s_med', models.BinaryField(default=False, verbose_name='Близость с мед учереждением')),
                ('blizost_s_metro', models.BinaryField(default=False, verbose_name='Близость с метро')),
                ('nalichie_otdelki', models.IntegerField(choices=[(1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, verbose_name='Наличие отделки')),
                ('opisaanaie', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Дом - аренда',
                'verbose_name_plural': 'Дома - аренда',
            },
        ),
        migrations.CreateModel(
            name='DomProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать на сайте'), (False, 'Не показывать на сайте')], default=True, verbose_name='Показывать/скрыть')),
                ('eto_luchoe_prodlozenie', models.IntegerField(choices=[(1, 'Нет'), (2, 'Да. Выводить только на странице лучших предложений'), (3, 'Да. Выводить на странице лучших предложений и главной')], default=1, verbose_name='Лучшее предложение?')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('nomer', models.CharField(max_length=50, verbose_name='Номер(id объекта)')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('price_bazovaia', models.FloatField(blank=True, null=True, verbose_name='Базовая цена руб.')),
                ('prrice_akzionnaia', models.FloatField(blank=True, null=True, verbose_name='Акционная цена руб')),
                ('obshaia_ploshad', models.FloatField(blank=True, null=True, verbose_name='Общая площадь (кв. м)')),
                ('naselenii_punkt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
                ('kordinati_na_karte', models.CharField(blank=True, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте')),
                ('ploshad_uchastka', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь участка (соток)')),
                ('ploshad_osnovnogo_doma', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь основного дома(кв.м)')),
                ('nalichie_gaza', models.BinaryField(default=False, verbose_name='Наличие газа в доме')),
                ('blizost_so_shkoloi', models.BinaryField(default=False, verbose_name='Близость со школой')),
                ('blizost_s_med', models.BinaryField(default=False, verbose_name='Близость с мед учереждением')),
                ('blizost_s_metro', models.BinaryField(default=False, verbose_name='Близость с метро')),
                ('nalichie_otdelki', models.IntegerField(choices=[(1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, verbose_name='Наличие отделки')),
                ('opisaanaie', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Дом - продажа',
                'verbose_name_plural': 'Дома - продажа',
            },
        ),
        migrations.CreateModel(
            name='VideoDomProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', verbose_name='Iframe код видео')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='nedvizka.DomProdaza', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Видео дома',
                'verbose_name_plural': 'Видео дома',
                'ordering': ['-index_sortirivki'],
            },
        ),
        migrations.CreateModel(
            name='VideoDomArendda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.TextField(help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', verbose_name='Iframe код видео')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_set', to='nedvizka.DomArenda', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Видео дома',
                'verbose_name_plural': 'Видео дома',
                'ordering': ['-index_sortirivki'],
            },
        ),
        migrations.CreateModel(
            name='PanoramiDomProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_code', models.TextField(help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', verbose_name='iframe код')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panorami_set', to='nedvizka.DomProdaza', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Панорамы домов',
                'verbose_name_plural': 'Панорамы домов',
                'ordering': ['-index_sortirivki'],
            },
        ),
        migrations.CreateModel(
            name='PanoramiArenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_code', models.TextField(help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', verbose_name='iframe код')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panorami_set', to='nedvizka.DomArenda', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Панорамы домов',
                'verbose_name_plural': 'Панорамы домов',
                'ordering': ['-index_sortirivki'],
            },
        ),
        migrations.CreateModel(
            name='FotoDomProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='nedvizka.DomProdaza', verbose_name='Дом')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото дома',
                'ordering': ['-index_sortirivki'],
            },
        ),
        migrations.CreateModel(
            name='FotoDomArenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='nedvizka.DomArenda', verbose_name='Дом')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото дома',
                'ordering': ['-index_sortirivki'],
            },
        ),
    ]
