# Generated by Django 3.0.13 on 2021-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domarenda',
            name='blizost_s_med',
            field=models.BooleanField(default=False, verbose_name='Близость с мед учереждением'),
        ),
        migrations.AlterField(
            model_name='domarenda',
            name='blizost_s_metro',
            field=models.BooleanField(default=False, verbose_name='Близость с метро'),
        ),
        migrations.AlterField(
            model_name='domarenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(default=False, verbose_name='Близость со школой'),
        ),
        migrations.AlterField(
            model_name='domarenda',
            name='nalichie_gaza',
            field=models.BooleanField(default=False, verbose_name='Наличие газа в доме'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_s_med',
            field=models.BooleanField(default=False, verbose_name='Близость с мед учереждением'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_s_metro',
            field=models.BooleanField(default=False, verbose_name='Близость с метро'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(default=False, verbose_name='Близость со школой'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_gaza',
            field=models.BooleanField(default=False, verbose_name='Наличие газа в доме'),
        ),
    ]
