# Generated by Django 3.0.13 on 2021-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dom',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AlterField(
            model_name='dom',
            name='iframe_panorami',
            field=models.CharField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', max_length=1000, null=True, verbose_name='Код панорами'),
        ),
        migrations.AlterField(
            model_name='dom',
            name='video',
            field=models.CharField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', max_length=1000, null=True, verbose_name='Ссылка на видео youtube'),
        ),
    ]
