# Generated by Django 3.0.13 on 2021-05-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domprodaza',
            name='filter_bassein',
            field=models.BooleanField(default=False, verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='filter_kotedzni_poselok',
            field=models.BooleanField(default=False, verbose_name='Коттеджный поселок'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='filter_peshai_dostupnost_k_pliazu',
            field=models.BooleanField(default=False, verbose_name='Пешая доступность к пляжу'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='filter_vid_na_moria',
            field=models.BooleanField(default=False, verbose_name='Вид на моря'),
        ),
    ]
