# Generated by Django 3.0.13 on 2021-04-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nedvizka', '0003_auto_20210418_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedvizkaPanelUpravleniaPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_nedvizkapanelupravleniapluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('pokazat_kartu', models.BooleanField(default=True, verbose_name='Показывать карту')),
                ('pokazat_sortirovku', models.BooleanField(default=True, verbose_name='Показывать сортировку')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSS класс')),
                ('css_style', models.CharField(blank=True, max_length=1000, null=True, verbose_name='CSS стиль')),
            ],
            options={
                'verbose_name': 'Недвижка. Избранное',
                'verbose_name_plural': 'Недвижка. Избранное',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
