# Generated by Django 3.0.13 on 2021-04-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0005_nedvizkaspisokobiectovpluginpluginsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='fotodomov',
            name='dom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='nedvizka.Dom', verbose_name='Дом'),
        ),
    ]
