# Generated by Django 3.0.13 on 2021-06-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0006_auto_20210601_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='domarenda',
            name='akzia',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Акция/спец цена'),
        ),
        migrations.AddField(
            model_name='domarenda',
            name='price_itogovaia',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Цена для поиска'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='akzia',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Акция/спец цена'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='price_itogovaia',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Цена для поиска'),
        ),
    ]
