# Generated by Django 3.0.13 on 2021-04-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0006_auto_20210419_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotodomov',
            options={'ordering': ['-index_sortirivki'], 'verbose_name': 'Фото дома', 'verbose_name_plural': 'Фото дома'},
        ),
        migrations.AddField(
            model_name='fotodomov',
            name='index_sortirivki',
            field=models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки'),
        ),
    ]
