# Generated by Django 3.0.13 on 2021-04-21 02:01

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0007_auto_20210420_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dom',
            name='opisaanaie',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание для страницы детальной информации'),
        ),
    ]
