# Generated by Django 3.0.13 on 2021-04-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0008_auto_20210421_1444'),
        ('nedvizka', '0008_auto_20210421_1101'),
    ]

    operations = [
    ]
