# Generated by Django 3.0.13 on 2021-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0009_merge_20210421_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodomov',
            name='video',
            field=models.TextField(help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', verbose_name='Iframe код видео'),
        ),
    ]
