# Generated by Django 3.0.13 on 2021-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0009_auto_20210601_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domarenda',
            name='price_bazovaia',
            field=models.FloatField(default=0, verbose_name='Базовая цена руб.'),
        ),
        migrations.AlterField(
            model_name='domarenda',
            name='price_itogovaia',
            field=models.FloatField(default=0, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='domarenda',
            name='prrice_akzionnaia',
            field=models.FloatField(default=0, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='price_bazovaia',
            field=models.FloatField(default=0, verbose_name='Базовая цена руб.'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(default=0, verbose_name='Акционная цена руб'),
        ),
    ]
