# Generated by Django 3.0.13 on 2021-04-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('nedvizka', '0010_auto_20210421_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Spezialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('gorod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nedvizka.Gorod', verbose_name='Город')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалист',
            },
        ),
    ]
