# Generated by Django 3.0.13 on 2021-05-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('nedvizka', '0011_gorod_spezialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedvizkaFiltriPoiskaPluginPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='nedvizka_nedvizkafiltripoiskapluginpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('tip_nedvizki', models.CharField(choices=[('dom_prodaza', 'Дом-продажа'), ('dom_arenda', 'Дом-аренда')], max_length=255, verbose_name='Тип недвижки')),
            ],
            options={
                'verbose_name': 'Недвижка. Фильтры/поиск',
                'verbose_name_plural': 'Недвижка. Фильтры/поиск',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='spezialist',
            name='gorod',
        ),
        migrations.RemoveField(
            model_name='spezialist',
            name='photo',
        ),
        migrations.AlterField(
            model_name='dom',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.DeleteModel(
            name='Gorod',
        ),
        migrations.DeleteModel(
            name='Spezialist',
        ),
    ]
