# Generated by Django 3.0.13 on 2021-08-03 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('nedvizka', '0014_auto_20210803_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaoetaznoiPostroiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материал постройки малоэтажной стройки',
                'verbose_name_plural': 'Материалы постройки малоэтажной стройки',
            },
        ),
        migrations.CreateModel(
            name='TipMaloetaznoiPostroiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Материал постройки малоэтажной стройки',
                'verbose_name_plural': 'Материалы постройки малоэтажной стройки',
            },
        ),
        migrations.CreateModel(
            name='MaloEtaznoeStroitelstvoProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать'), (False, 'Скрыть')], default=True, verbose_name='Показывать/скрыть')),
                ('nazvanie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price_bazovaia', models.FloatField(default=0, verbose_name='Базовая цена руб.')),
                ('prrice_akzionnaia', models.FloatField(default=0, verbose_name='Акционная цена руб')),
                ('price_itogovaia', models.FloatField(default=0, verbose_name='Цена для поиска')),
                ('akzia', models.BooleanField(default=False, editable=False, verbose_name='Акция/спец цена')),
                ('ploshad_osnovnogo_doma', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Площадь основного дома(кв.м)')),
                ('kolvo_etazei', models.IntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('kolvo_komnat', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('opisaanaie', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание')),
                ('material_postroiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nedvizka.MaterialMaoetaznoiPostroiki', verbose_name='Материал')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
                ('tip_maloetaznoi_postroiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nedvizka.TipMaloetaznoiPostroiki', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Малоэтажное строительство - продажа',
                'verbose_name_plural': 'Малоэтажное строительство - продажа',
            },
        ),
        migrations.CreateModel(
            name='FotoMaloEtaznoeStroitelstvoProdaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sortirivki', models.IntegerField(default=0, help_text='Чем больше тем раньше выведет', verbose_name='Индекс сортировки')),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foto_set', to='nedvizka.MaloEtaznoeStroitelstvoProdaza', verbose_name='Дом')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото дома',
                'ordering': ['-index_sortirivki'],
            },
        ),
    ]
