# Generated by Django 3.0.13 on 2021-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0015_fotomaloetaznoestroitelstvoprodaza_maloetaznoestroitelstvoprodaza_materialmaoetaznoipostroiki_tipmal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='kolvo_etazei',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество этажей'),
        ),
    ]
