# Generated by Django 3.0.13 on 2021-08-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0017_auto_20210803_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uchactkiarenda',
            name='kordinati_na_karte',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='kordinati_na_karte',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='nalichie_gaza',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='nalichie_otdelki',
        ),
        migrations.AddField(
            model_name='uchactkiprodaza',
            name='electrichestvo',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Электричество'),
        ),
        migrations.AddField(
            model_name='uchactkiprodaza',
            name='ostanovki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановки'),
        ),
        migrations.AddField(
            model_name='uchactkiprodaza',
            name='vodoprovod',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Водопровод'),
        ),
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='blizost_s_med',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Близость с мед учереждением'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='blizost_s_metro',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Близость с метро'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Близость со школой'),
        ),
    ]
