# Generated by Django 3.0.13 on 2021-08-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0019_auto_20210804_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uchactkiprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Участки - продажа', 'verbose_name_plural': 'Участки - продажа'},
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='electrichestvo',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Электричество'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='nalichie_vnesheni_otdelki',
            field=models.IntegerField(choices=[(None, '---'), (1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, verbose_name='Наличие внешней отделки'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='ostanovki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановки'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='ploshad_ouchastka',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка'),
        ),
        migrations.AddField(
            model_name='domprodaza',
            name='vodoprovod',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Водопровод'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_otdelki',
            field=models.IntegerField(choices=[(None, '---'), (1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, verbose_name='Наличие внутренней отделки'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='ploshad_osnovnogo_doma',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь основного дома(кв.м)'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name=    'obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка (м2)'),
        ),
    ]
