# Generated by Django 3.0.13 on 2021-08-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0021_auto_20210804_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_vnesheni_otdelki',
            field=models.BooleanField(choices=[(None, '---'), (1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, verbose_name='Наличие внешней отделки'),
        ),
    ]
