# Generated by Django 3.0.13 on 2021-08-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0022_auto_20210804_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_vnesheni_otdelki',
            field=models.IntegerField(choices=[(None, '---'), (1, 'Без отделки'), (2, 'Есть')], default=1, verbose_name='Наличие внешней отделки'),
        ),
    ]
