# Generated by Django 3.0.13 on 2021-08-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0024_auto_20210804_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
    ]
