# Generated by Django 3.0.13 on 2021-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0025_auto_20210804_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_s_med',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Близость с мед учереждением'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_s_metro',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Близость с метро'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Близость со школой'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_gaza',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='Наличие газа в доме'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_otdelki',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (1, 'Без отделки'), (2, 'Черновая'), (3, 'С ремонтом')], default=1, null=True, verbose_name='Наличие внутренней отделки'),
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='nalichie_vnesheni_otdelki',
            field=models.IntegerField(blank=True, choices=[(None, '---'), (1, 'Без отделки'), (2, 'Есть')], default=1, null=True, verbose_name='Наличие внешней отделки'),
        ),
    ]
