# Generated by Django 3.0.13 on 2021-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0026_auto_20210804_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='adres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AddField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='naselenii_punkt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь дома (кв. м)'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь дома (кв. м)'),
        ),
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
    ]
