# Generated by Django 3.0.13 on 2021-08-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0027_auto_20210804_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvartirapervichkaprodaza',
            name='ostanovki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановки'),
        ),
        migrations.AlterField(
            model_name='komerchiskiearenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaarenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком/садиком'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='nalichie_gaza',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Наличие газа'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь дома (кв. м)'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaarenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='nezeliearenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='uchactkiarenda',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(blank=True, choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Близость со школой/садиком'),
        ),
    ]
