# Generated by Django 3.0.13 on 2021-08-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0028_auto_20210804_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotokvartiravtorichkaarenda',
            name='img',
        ),
        migrations.RemoveField(
            model_name='fotokvartiravtorichkaarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='kvartirapervichkaarenda',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='kvartiravtorichkaarenda',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='panoramikvartirapervichkaarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoramikvartirapervichkaprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoramikvartiravtorichkaarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoramikvartiravtorichkaprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokvartirapervichkaarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokvartirapervichkaprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokvartiravtorichkaarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokvartiravtorichkaprodaza',
            name='nedvizka',
        ),
        migrations.AddField(
            model_name='kvartiravtorichkaprodaza',
            name='ostanovki',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остановки'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='blizost_so_shkoloi',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Близость со школой/садиком/садиком'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='nalichie_gaza',
            field=models.BooleanField(choices=[(None, '---'), (True, 'Да'), (False, 'Нет')], default=False, verbose_name='Наличие газа'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь дома (кв. м)'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.DeleteModel(
            name='FotoKvartiraPervichkaArenda',
        ),
        migrations.DeleteModel(
            name='FotoKvartiraVtorichkaArenda',
        ),
        migrations.DeleteModel(
            name='KvartiraPervichkaArenda',
        ),
        migrations.DeleteModel(
            name='KvartiraVtorichkaArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiKvartiraPervichkaArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiKvartiraPervichkaProdaza',
        ),
        migrations.DeleteModel(
            name='PanoramiKvartiraVtorichkaArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiKvartiraVtorichkaProdaza',
        ),
        migrations.DeleteModel(
            name='VideoKvartiraPervichkaArenda',
        ),
        migrations.DeleteModel(
            name='VideoKvartiraPervichkaProdaza',
        ),
        migrations.DeleteModel(
            name='VideoKvartiraVtorichkaArenda',
        ),
        migrations.DeleteModel(
            name='VideoKvartiraVtorichkaProdaza',
        ),
    ]
