# Generated by Django 3.0.13 on 2021-08-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0029_auto_20210804_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramiuchactkiarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoramiuchactkiprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='uchactkiarenda',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='videouchactkiarenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videouchactkiprodaza',
            name='nedvizka',
        ),
        migrations.AddField(
            model_name='uchactkiprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AddField(
            model_name='uchactkiprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь дома (кв. м)'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.DeleteModel(
            name='FotoUchactkiArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiUchactkiArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiUchactkiProdaza',
        ),
        migrations.DeleteModel(
            name='UchactkiArenda',
        ),
        migrations.DeleteModel(
            name='VideoUchactkiArenda',
        ),
        migrations.DeleteModel(
            name='VideoUchactkiProdaza',
        ),
    ]
