# Generated by Django 3.0.13 on 2021-08-04 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('nedvizka', '0030_auto_20210804_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipKomerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать'), (False, 'Скрыть')], default=True, verbose_name='Показывать/скрыть')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка')),
                ('price_bazovaia', models.FloatField(default=0, verbose_name='Базовая цена руб.')),
                ('prrice_akzionnaia', models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб')),
                ('price_itogovaia', models.FloatField(default=0, editable=False, verbose_name='Цена для поиска')),
                ('akzia', models.BooleanField(default=False, editable=False, verbose_name='Акция/спец цена')),
                ('obshaia_ploshad', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)')),
                ('naselenii_punkt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('kordinati_na_karte', models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте')),
                ('opisaanaie', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Комерчиский - тип',
                'verbose_name_plural': 'Комерчиский - тип',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TipNeziloe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokazivat', models.BooleanField(choices=[(True, 'Показывать'), (False, 'Скрыть')], default=True, verbose_name='Показывать/скрыть')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка')),
                ('price_bazovaia', models.FloatField(default=0, verbose_name='Базовая цена руб.')),
                ('prrice_akzionnaia', models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб')),
                ('price_itogovaia', models.FloatField(default=0, editable=False, verbose_name='Цена для поиска')),
                ('akzia', models.BooleanField(default=False, editable=False, verbose_name='Акция/спец цена')),
                ('obshaia_ploshad', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)')),
                ('naselenii_punkt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
                ('adres', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('kordinati_na_karte', models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте')),
                ('opisaanaie', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Будет выводиться только если выбран шаблонное оформление страницы объекта', null=True, verbose_name='Описание')),
                ('nazvanie', models.CharField(max_length=255, verbose_name='Название')),
                ('previu', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Нежилые - тип',
                'verbose_name_plural': 'Нежилые - тип',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='fotonezeliearenda',
            name='img',
        ),
        migrations.RemoveField(
            model_name='fotonezeliearenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='komerchiskiearenda',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='nezeliearenda',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='panoramikomerchiskiearenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoramikomerchiskieprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoraminezeliearenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='panoraminezelieprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokomerchiskiearenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videokomerchiskieprodaza',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videonezeliearenda',
            name='nedvizka',
        ),
        migrations.RemoveField(
            model_name='videonezelieprodaza',
            name='nedvizka',
        ),
        migrations.AlterModelOptions(
            name='domprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Дом - продажа', 'verbose_name_plural': 'Дома - продажа'},
        ),
        migrations.AlterModelOptions(
            name='komerchiskieprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Комерчиские - продажа', 'verbose_name_plural': 'Комерчиские - продажа'},
        ),
        migrations.AlterModelOptions(
            name='kvartirapervichkaprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Квартира первичка - продажа', 'verbose_name_plural': 'Квартира первичка - продажа'},
        ),
        migrations.AlterModelOptions(
            name='kvartiravtorichkaprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Квартира вторичка - продажа', 'verbose_name_plural': 'Квартира вторичка - продажа'},
        ),
        migrations.AlterModelOptions(
            name='maloetaznoestroitelstvoprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Малоэтажное строительство - продажа', 'verbose_name_plural': 'Малоэтажное строительство - продажа'},
        ),
        migrations.AlterModelOptions(
            name='nezelieprodaza',
            options={'ordering': ['-id'], 'verbose_name': 'Нежилые - продажа', 'verbose_name_plural': 'Нежилые - продажа'},
        ),
        migrations.RemoveField(
            model_name='komerchiskieprodaza',
            name='blizost_s_med',
        ),
        migrations.RemoveField(
            model_name='komerchiskieprodaza',
            name='blizost_s_metro',
        ),
        migrations.RemoveField(
            model_name='komerchiskieprodaza',
            name='blizost_so_shkoloi',
        ),
        migrations.RemoveField(
            model_name='komerchiskieprodaza',
            name='nalichie_gaza',
        ),
        migrations.RemoveField(
            model_name='komerchiskieprodaza',
            name='nalichie_otdelki',
        ),
        migrations.RemoveField(
            model_name='nezelieprodaza',
            name='blizost_s_med',
        ),
        migrations.RemoveField(
            model_name='nezelieprodaza',
            name='blizost_s_metro',
        ),
        migrations.RemoveField(
            model_name='nezelieprodaza',
            name='blizost_so_shkoloi',
        ),
        migrations.RemoveField(
            model_name='nezelieprodaza',
            name='nalichie_gaza',
        ),
        migrations.RemoveField(
            model_name='nezelieprodaza',
            name='nalichie_otdelki',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='blizost_s_med',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='blizost_s_metro',
        ),
        migrations.RemoveField(
            model_name='uchactkiprodaza',
            name='blizost_so_shkoloi',
        ),
        migrations.AlterField(
            model_name='domprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='kvartirapervichkaprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='kvartiravtorichkaprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='maloetaznoestroitelstvoprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='kordinati_na_karte',
            field=models.CharField(blank=True, editable=False, help_text='Например "44.533249, 33.455248" без кавычек (https://snipp.ru/tools/address-coord)', max_length=255, null=True, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='price_itogovaia',
            field=models.FloatField(default=0, editable=False, verbose_name='Цена для поиска'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='prrice_akzionnaia',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Акционная цена руб'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='uchactkiprodaza',
            name='obshaia_ploshad',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь (кв. м)'),
        ),
        migrations.DeleteModel(
            name='FotoKomerchiskieArenda',
        ),
        migrations.DeleteModel(
            name='FotoNezelieArenda',
        ),
        migrations.DeleteModel(
            name='KomerchiskieArenda',
        ),
        migrations.DeleteModel(
            name='NezelieArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiKomerchiskieArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiKomerchiskieProdaza',
        ),
        migrations.DeleteModel(
            name='PanoramiNezelieArenda',
        ),
        migrations.DeleteModel(
            name='PanoramiNezelieProdaza',
        ),
        migrations.DeleteModel(
            name='VideoKomerchiskieArenda',
        ),
        migrations.DeleteModel(
            name='VideoKomerchiskieProdaza',
        ),
        migrations.DeleteModel(
            name='VideoNezelieArenda',
        ),
        migrations.DeleteModel(
            name='VideoNezelieProdaza',
        ),
        migrations.AddField(
            model_name='komerchiskieprodaza',
            name='tip_komerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nedvizka.TipKomerch'),
        ),
        migrations.AddField(
            model_name='nezelieprodaza',
            name='tip_komerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nedvizka.TipNeziloe'),
        ),
    ]
