# Generated by Django 3.0.13 on 2021-08-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0031_auto_20210804_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipkomerch',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='akzia',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='kordinati_na_karte',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='naselenii_punkt',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='obshaia_ploshad',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='opisaanaie',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='pokazivat',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='price_bazovaia',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='price_itogovaia',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='prrice_akzionnaia',
        ),
        migrations.RemoveField(
            model_name='tipkomerch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='akzia',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='kordinati_na_karte',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='naselenii_punkt',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='obshaia_ploshad',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='opisaanaie',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='pokazivat',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='previu',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='price_bazovaia',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='price_itogovaia',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='prrice_akzionnaia',
        ),
        migrations.RemoveField(
            model_name='tipneziloe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='komerchiskieprodaza',
            name='tip_komerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nedvizka.TipKomerch', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='nezelieprodaza',
            name='tip_komerch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nedvizka.TipNeziloe', verbose_name='Тип'),
        ),
    ]
