# Generated by Django 3.0.13 on 2021-08-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nedvizka', '0032_auto_20210804_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nezelieprodaza',
            old_name='tip_komerch',
            new_name='tip_neziloe',
        ),
    ]
