# Generated by Django 3.0.13 on 2021-05-06 14:16

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazmerTextaPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='razmer_texta_plugin_razmertextapluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('tag_type', models.CharField(default='p', max_length=10, verbose_name='Тег')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Текст')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прочие классы')),
                ('all_style', models.TextField(blank=True, null=True, verbose_name='col стили')),
                ('sm_style', models.TextField(blank=True, null=True, verbose_name='sm стили')),
                ('md_style', models.TextField(blank=True, null=True, verbose_name='md стили')),
                ('lg_style', models.TextField(blank=True, null=True, verbose_name='lg стили')),
                ('xl_style', models.TextField(blank=True, null=True, verbose_name='xl стили')),
            ],
            options={
                'verbose_name': 'Мой стиль',
                'verbose_name_plural': 'Мой стиль',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
