# Generated by Django 3.0.13 on 2021-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razmer_texta_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
