# Generated by Django 3.0.13 on 2021-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razmer_texta_plugin', '0002_auto_20210506_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razmertextapluginsetting',
            name='lg_style',
        ),
        migrations.RemoveField(
            model_name='razmertextapluginsetting',
            name='md_style',
        ),
        migrations.RemoveField(
            model_name='razmertextapluginsetting',
            name='sm_style',
        ),
        migrations.RemoveField(
            model_name='razmertextapluginsetting',
            name='xl_style',
        ),
        migrations.AddField(
            model_name='razmertextapluginsetting',
            name='col_size',
            field=models.CharField(blank=True, help_text='с указанием px/%/pt', max_length=255, null=True, verbose_name='col размер'),
        ),
        migrations.AddField(
            model_name='razmertextapluginsetting',
            name='lg_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='lg размер'),
        ),
        migrations.AddField(
            model_name='razmertextapluginsetting',
            name='md_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='md размер'),
        ),
        migrations.AddField(
            model_name='razmertextapluginsetting',
            name='sm_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sm размер'),
        ),
        migrations.AddField(
            model_name='razmertextapluginsetting',
            name='xl_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='xl размер'),
        ),
    ]
