# Generated by Django 3.0.13 on 2021-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razmer_texta_plugin', '0003_auto_20210506_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razmertextapluginsetting',
            name='tag_type',
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='all_style',
            field=models.TextField(blank=True, null=True, verbose_name='Прочие стили стили'),
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='col_size',
            field=models.CharField(blank=True, help_text='с указанием px/pt и прочего', max_length=255, null=True, verbose_name='col размер'),
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='lg_size',
            field=models.CharField(blank=True, help_text='с указанием px/pt и прочего', max_length=255, null=True, verbose_name='lg размер'),
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='md_size',
            field=models.CharField(blank=True, help_text='с указанием px/pt и прочего', max_length=255, null=True, verbose_name='md размер'),
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='sm_size',
            field=models.CharField(blank=True, help_text='с указанием px/pt и прочего', max_length=255, null=True, verbose_name='sm размер'),
        ),
        migrations.AlterField(
            model_name='razmertextapluginsetting',
            name='xl_size',
            field=models.CharField(blank=True, help_text='с указанием px/pt и прочего', max_length=255, null=True, verbose_name='xl размер'),
        ),
    ]
