# Generated by Django 3.0.13 on 2021-03-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAlbomPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='foto_albom_fotoalbompluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('width', models.PositiveIntegerField(default=250, help_text='Если сомневаетесь, то не меняйте=}', verbose_name='Ширина при обрезке')),
                ('height', models.PositiveIntegerField(default=150, help_text='Если сомневаетесь, то не меняйте=}', verbose_name='Высота при обрезке')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбом',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FotoIzAlboma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_sortirovki', models.IntegerField(default=0, help_text='Чем больше, тем раньше отобразиться фото в альбоме', verbose_name='Индекс сортировки')),
                ('fotoalbom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_iz_alboma', to='foto_albom.FotoAlbomPluginSetting')),
                ('img', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='img_iz_alboma', to=settings.FILER_IMAGE_MODEL, verbose_name='Фото из фотоальбома')),
            ],
            options={
                'verbose_name': 'Фото из фотоальбома',
                'verbose_name_plural': 'Фото из фотоальбома',
                'ordering': ['-index_sortirovki'],
            },
        ),
    ]
