# Generated by Django 3.0.13 on 2021-03-15 07:34

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtziviDvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='otzivi_otzividvpluginsetting', serialize=False, to='cms.CMSPlugin')),
                ('avtor', models.TextField(blank=True, null=True, verbose_name='Автор')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью автора')),
                ('opisanie', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Датв')),
                ('ssilla', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('ikonka_otzivnika', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка сайта где отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы - слайд',
                'verbose_name_plural': 'Отзывы - слайды',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OtziviLvPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='otzivi_otzivilvpluginsetting', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'verbose_name': 'Отзывы слайдер',
                'verbose_name_plural': 'Отзывы слайдеры',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
