# Generated by Django 3.0.13 on 2021-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzivi', '0002_auto_20210315_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otzividvpluginsetting',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='otzividvpluginsetting',
            name='opisanie',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
    ]
