# Generated by Django 3.0.13 on 2021-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzivi', '0003_auto_20210315_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otzividvpluginsetting',
            name='ikonka_otzivnika',
        ),
        migrations.AddField(
            model_name='otzividvpluginsetting',
            name='nazvanie_otzivnika',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отзывника'),
        ),
    ]
